# Notebook 24: Stress

## Introduction

Like strain, stress is a symmetric tensor. In 3D, the stress tensor $\sigma_{ij}$ has nine components: 

$$
\sigma_{i j}=\left[\begin{array}{lll}
\sigma_{11} & \sigma_{12} & \sigma_{13} \\
\sigma_{21} & \sigma_{22} & \sigma_{23} \\
\sigma_{31} & \sigma_{32} & \sigma_{33}
\end{array}\right]
$$

These are the tractions (force/area) acting on the faces of a small cube, whose sides are parallel to the axes of the coordinate system:

<img src="../figures/stress_components.png" alt="stress_components" width="350" style="display: block; margin: 0 auto"/><br><br>

As you can see, for the cube not to rotate about one of the axes, $\sigma_{12} = \sigma_{21}$, $\sigma_{23} = \sigma_{32}$, and $\sigma_{13} = \sigma_{31}$. Thus, the stress tensor is a symmetric tensor ($\sigma_{ij} = \sigma_{ji}$) that is defined by six components.

### Cauchy's law

The stress tensor relates two vectors, the traction on a plane, $\mathbf{t}$, and the pole to the plane, $\mathbf{p}$. This is expressed by Cauchy's law ([Allmendinger et al., 2012](https://www.cambridge.org/core/books/structural-geology-algorithms/C5AB97C135925A5D49726B741738DCA9)):

$$
t_i=\sigma_{i j} p_j
$$

<img src="../figures/cauchy_law.png" alt="cauchy_law" width="350" style="display: block; margin: 0 auto"/><br><br>

### Transformation of the stress tensor

If we know the components of the stress tensor in one coordinate system $\mathbf{X_1X_2X_3}$, we can calculate the components of the tensor in another coordinate system $\mathbf{X'_1X'_2X'_3}$ ([Allmendinger et al., 2012](https://www.cambridge.org/core/books/structural-geology-algorithms/C5AB97C135925A5D49726B741738DCA9)):

$$
\sigma_{i j}^{\prime}=a_{i k} a_{j l} \sigma_{k l}
$$

where $\mathbf{a}$ is the transformation matrix between the new and the old coordinate system.

### Principal axes of stress

Since stress is a symmetric tensor, there is one orientation of the coordinate system for which the non-diagonal components of the tensor are zero, and only normal tractions act on the planes perpendicular to the coordinate axes. These normal tractions are the principal stresses: $\sigma_1$ is the maximum, $\sigma_2$ is the intermediate, and $\sigma_3$ is the minimum principal stress.

## Python functions

1. The function [cauchy](../functions/cauchy.py) calculates the tractions acting on a plane of any orientation, in a Cartesian coordinate system of any orientation. This function uses function [dircos_axes](../functions/dircos_axes.py) to calculate the direction cosines of the $\mathbf{X_1X_2X_3}$ axes, from the trend and plunge of $\mathbf{X_1}$ and the trend of $\mathbf{X_3}$.

2. The function [tranform_stress](../functions/transform_stress.py) transforms the stress tensor from a Cartesian coordinate system of a given orientation to another orientation.

3. The function [principal_stress](../functions/principal_stress.py) calculates the principal stresses and their orientations for a given stress tensor in a Cartesian coordinate system of any orientation.

Note: In these three functions, the angles must be input in radians.

## Application

Let's use these functions to solve the following problem: $\sigma_1$, $\sigma_2$ and $\sigma_3$ are 40, 30 and 20 MPa, respectively. $\sigma_1$ is vertical, and $\sigma_3$ is horizontal and oriented N-S.

1. Compute the tractions parallel to the principal stress directions, acting on a plane with orientation 040/65 (strike and dip, RHR).

2. Compute the stress tensor on a new coordinate system with $\mathbf{X_1}$ oriented 030/45 (trend and plunge), and $\mathbf{X_3}$ trending 210.

3. Demonstrate that the new components of the stress tensor represent the same tensor, by computing the principal stresses from the new components.

In [ ]:
import sys, os
import numpy as np

# this makes visible our functions folder
sys.path.append(os.path.abspath(os.path.join("..", "functions")))

# import functions cauchy, transform_stress, and principal_stress
from cauchy import cauchy
from transform_stress import transform_stress
from principal_stress import principal_stress

# input stress tensor in principal coordinates
stress = np.array([[40, 0, 0], [0, 30, 0], [0, 0, 20]])

# trend and plunge of X1 axis, and trend of X3 axis
tx1, px1, tx3 = np.radians([0, 90, 0])

# plane orientation
stk, dip = np.radians([40, 65])

# 1. X1, X2, X3 tracions on plane
t, pt = cauchy(stress, tx1, px1, tx3, stk, dip)
print("1. X1, X2, X3 tractions on plane:", t.round(2), "\n")

# 2. transform stress to a new coordinate system
ntx1, npx1, ntx3 = np.radians([30, 45, 210])
nstress = transform_stress(stress, tx1, px1, tx3, ntx1, npx1, ntx3)
print("2. Stress in new coordinate system:\n", nstress.round(2), "\n")

# 3. principal stresses from new components
ps, _ = principal_stress(nstress, ntx1, npx1, ntx3)
ps[:,1:3] = np.degrees(ps[:,1:3]) # convert to degrees

print("3. Principal stresses in new coordinate system:")
print(f"Sigma1 = {ps[0,0]:.2f} MPa, T = {ps[0,1]:.1f}, P = {ps[0,2]:.1f}")
print(f"Sigma2 = {ps[1,0]:.2f} MPa, T = {ps[1,1]:.1f}, P = {ps[1,2]:.1f}")
print(f"Sigma3 = {ps[2,0]:.2f} MPa, T = {ps[2,1]:.1f}, P = {ps[2,2]:.1f}")

1. X1, X2, X3 tractions on plane: [16.9  20.83 11.65] 

2. Stress in new coordinate system:
 [[31.25  3.06  8.75]
 [ 3.06 27.5  -3.06]
 [ 8.75 -3.06 31.25]] 

3. Principal stresses in new coordinate system:
Sigma1 = 40.00 MPa, T = 147.0, P = -90.0
Sigma2 = 30.00 MPa, T = 270.0, P = -0.0
Sigma3 = 20.00 MPa, T = 180.0, P = 0.0


The principal stresses computed from the new components of the stress tensor are the same than the input principal stresses. 

Task:

1. Change the orientation of $\sigma_1$ to 045/00. How do the results change?
