# Notebook 2: Lines as vectors

Although we can express lines by trend and plunge, it is difficult to operate on them using these measurements. In this lecture, we will look at how to express lines as vectors.

## The NED coordinate system

The first thing we need is a Cartesian coordinate system in three-dimensions. We'll choose a coordinate system as shown below, with $\mathbf{X_1}-\mathbf{X_2}-\mathbf{X_3}$ axes equal to North - East - Down. This NED coordinate system is right handed. That means that if you hold your right hand with the thumb pointing along $\mathbf{X_1}$ (North), the other fingers will curl from $\mathbf{X_2}$ (East) to $\mathbf{X_3}$ (Down):

<img src="../figures/NED.png" alt="NED" width="500" style="display: block; margin: 0 auto"/><br><br>

## Vectors

A vector is a mathematical entity (a tensor of rank 1) that has both magnitude and orientation. In a 3D Cartesian coordinate system, vectors are defined by three components, which are the lengths of the vector along the axes of the coordinate system:

$$\mathbf{v}=[v_1,v_2,v_3]$$

The magnitude (or length) of a vector is:

$$v=(v_1^2+v_2^2+v_3^2)^{1/2}$$

And if we divide the vector's components by its magnitude, we obtain a unit vector, a vector of length 1.0:

$$\mathbf{\hat{v}}=[v_1/v,v_2/v,v_3/v]$$

The components of a unit vector are the cosines of the angles the vector makes with the axes of the coordinate system. These are called the direction cosines:

$$\mathbf{\hat v} = [\cos\alpha,\cos\beta,\cos\gamma]$$

where $\cos\alpha$ is the cosine of the angle between the vector and $\mathbf{X_1}$, $\cos\beta$ is the cosine of the angle between the vector and $\mathbf{X_2}$, and $\cos\gamma$ is the cosine of the angle between the vector and $\mathbf{X_3}$.

## Lines as unit vectors

A line can be expressed as a unit vector (red line in figure below): 

<img src="../figures/line_unit_vector.png" alt="line_unit_vector" width="500" style="display: block; margin: 0 auto"/><br><br>

In a NED coordinate system, the direction cosines of a line are (Allmendinger et al., 2012):

$$\cos\alpha=\cos(trend)\cos(plunge)$$

$$\cos\beta=\sin(trend)\cos(plunge)$$

$$\cos\gamma=\sin(plunge)$$

This allows converting the line from spherical coordinates (trend and plunge) to Cartesian coordiantes (direction cosines).

## Unit vectors as lines

We can also convert the line from Cartesian coordinates (direction cosines) to spherical coordinates (trend and plunge) (Allmendinger et al., 2012):

$$plunge=\arcsin(\cos\gamma)$$

$$trend=\arctan\left(\frac{\cos\beta}{\cos\alpha}\right)$$

However, in the $trend$ equation there is a minor problem because the $\arctan$ function delivers two possible azimuth angles of opposite direction. Therefore, one should decide which angle to use based on the sign of the direction cosines.

## Python functions

1. Function [sph_to_cart](../functions/sph_to_cart.py) converts a line from spherical coordinates (trend and plunge) to Cartesian coordinates (direction cosines).
2. Function [cart_to_sph](../functions/cart_to_sph.py) converts a line from Cartesian coordinates (direction cosines) to sperical coordinates (trend and plunge).

## Application

Now let's do an exercise: Compute the direction cosines of the following lines (trend/plunge): 252/45, 295/36, 144/67, 044/23:

In [1]:
# this makes visible our functions folder
import sys, os
sys.path.append(os.path.abspath("../functions"))

# import our functions
from sph_to_cart import sph_to_cart
from cart_to_sph import cart_to_sph

# import numpy
import numpy as np

# lines in radians
lines = np.radians([[252, 45], [295, 36], [144, 67], [44, 23]])

# initialize direction cosines
dcos = np.zeros((lines.shape[0], 3))

# calculate the direction cosines
for i in range(lines.shape[0]):
    dcos[i,0], dcos[i,1], dcos[i,2] = sph_to_cart(lines[i,0], lines[i,1])
    
# print the direction cosines
print(dcos)

[[-0.21850801 -0.67249851  0.70710678]
 [ 0.34190536 -0.7332184   0.58778525]
 [-0.31610812  0.22966599  0.92050485]
 [ 0.66215578  0.6394364   0.39073113]]


And the trend and plunge of the lines from the direction cosines:

In [2]:
# calculate the trend and plunge from direction cosines
for i in range(dcos.shape[0]):
    lines[i,0], lines[i,1] = cart_to_sph(dcos[i,0], dcos[i,1], dcos[i,2])

# print the lines in degrees
print(np.rad2deg(lines))

[[252.  45.]
 [295.  36.]
 [144.  67.]
 [ 44.  23.]]


Does this make sense? Try guessing the trend and plunge of the line from its direction cosines, and the direction cosines from the trend and plunge.